#ifndef LIBFUSECC_GLOBAL_H
#define LIBFUSECC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBFUSECC_LIBRARY)
#  define LIBFUSECCSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBFUSECCSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBFUSECC_GLOBAL_H
